### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by builtbyproxy** [manjureddy7/Tech-Links#1]
Hey @manjureddy7 

Do the same thing you've done in this commit: dd38389a2f4d034865efaa7313b4051b3433db16

to this file: 
https://github.com/manjureddy7/Tech-Links/blob/master/src/Firebase.js

Anyone including me can clone your repo and just disable your login wall and go straight through. 

Happy to help as needed 👍 

Also, perhaps make this a private repo?

**Comment by manjureddy7** [comment]
Hey @builtbyproxy Thanks a lot Man.

**Comment by builtbyproxy** [comment]
Any time! let me know if there are any confusions with this stuff 👍

**Comment by builtbyproxy** [comment]
Also you misunderstood what I said, don't gitignore your `firebase.js` file
instead replace the values inside it with values using `process.env.` and then add the real values to the `.env` file

**Comment by manjureddy7** [comment]
Thanks alot. I'm newbie in this stuff. Still figuring out.

**Comment by manjureddy7** [comment]
I have seen your repos. Looks like you are good in Apollo , graphQl. Can you recommend me how to start? I'm beginner in this

**Comment by manjureddy7** [comment]
@builtbyproxy

**Comment by builtbyproxy** [comment]
Hey mate

What's your reason to use GraphQL? And are you familiar with REST APIs?

**Comment by manjureddy7** [comment]
Hey @builtbyproxy . Yes i have been using REST APIs till now. Just want to familiarise in GraphQL

**Comment by builtbyproxy** [comment]
I would recommend you start here:
https://www.apollographql.com/docs/tutorial/introduction/

Let me know how it goes

**Comment by manjureddy7** [comment]
Sure. Thanks Mate @builtbyproxy

**Comment by builtbyproxy** [comment]
Let me know how you go!

**Comment by manjureddy7** [comment]
@builtbyproxy Curious to know, how do you know about my branch? and what made you to dig into it?

**Comment by builtbyproxy** [comment]
It came up here:
https://shhgit.darkport.co.uk/

**Comment by manjureddy7** [comment]
@builtbyproxy  looking it for the first time. Thanks mate

**Comment by manjureddy7** [comment]
@builtbyproxy  I have one doubt in using env for production. When i moved all secured info from firebase to env file, i'm getting error in production. In localhost/local development it is working as expected.

**Comment by builtbyproxy** [comment]
What do you mean in production? Where are you running it? 
Also whats your error? Try to always provide as much info as possible so I dont have to ask these questions to save time :) 

There's a chance you just dont have it defined in the production environment. Alternatively depending where it's hosted it may just be called something else 👍
